[package]
name = "scinfo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
const-random = "0.1.18"
const-str = "0.5.7"
json = "0.12.4"
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0.215"
serde_json = "1.0.132"
tokio = { version = "1", features = ["full"] }
